spring:
  application:
    name: final_spring

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/finaldb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          # 구글
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile,email
            # 구글의 기본 redirect-uri는 {baseUrl}/login/oauth2/code/google 이므로 명시하지 않아도 됩니다.

          # 카카오
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope: profile_nickname, account_email

          # Github
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            # github 콜백 URL 명시적 지정 (선택사항이나 확실히 하기 위해)
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            scope: read:user,user:email

        provider:
          # 카카오 공급자 정보 (구글과 깃허브는 기본 제공되므로 카카오만 명시)
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  elasticsearch:
    uris: http://${ELASTICSEARCH_HOST:localhost}:9200

jwt:
  secret: ${JWT_SECRET}

app:
  frontend:
    url: http://localhost:5173

server:
  port: 8090
  servlet:
    context-path: "/api"
  forward-headers-strategy: native

llm:
  service-url: http://localhost:8001

aws:
  s3:
    bucket: ${AWS_S3_BUCKET}
  region: ${AWS_REGION}
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true